# Generated by Django 5.0.4 on 2025-03-11 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('article_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('article_pdf', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('situation', models.CharField(default='Awaiting review', max_length=20)),
                ('author_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_Type', models.CharField(default='author', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
