# Generated by Django 5.0.4 on 2025-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
