# Generated by Django 5.0.4 on 2025-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_article_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='situation',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='upload_date',
        ),
    ]
