# Generated by Django 5.0.4 on 2025-03-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projectapp.article'),
        ),
    ]
