# Generated by Django 5.1.7 on 2025-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_review_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anonymized_pdf',
            field=models.FileField(blank=True, null=True, upload_to='anon_pdfs/'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
