# Generated by Django 5.1.7 on 2025-03-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_reviewer_logs_review_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
