# Generated by Django 5.1.7 on 2025-03-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_article_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('rect', models.JSONField()),
                ('placeholder', models.CharField(max_length=20)),
                ('original_text', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.article')),
            ],
        ),
    ]
