# Generated by Django 5.1.7 on 2025-03-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_anonymizeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projectapp.article'),
        ),
    ]
