# Generated by Django 5.1.7 on 2025-04-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='encrypted_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
