# Generated by Django 5.1.7 on 2025-04-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_article_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anonymized_pdf',
            field=models.FileField(blank=True, null=True, upload_to='final_pdfs/'),
        ),
    ]
