# Generated by Django 5.1.7 on 2025-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_alter_article_anonymized_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='final_pdfs/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='anonymized_pdf',
            field=models.FileField(blank=True, null=True, upload_to='anon_pdfs/'),
        ),
    ]
